# Generated by Django 5.0.1 on 2024-02-04 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitTrack', '0002_fooditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='Carbohydrates',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='Cholesterol',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='Fiber_Content',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='Potassium',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='Protein',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='Saturated_fat',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='Sodium',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='Sugar',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='Total_Fat',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='user',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='calories',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitTrack.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
