# Generated by Django 5.0.1 on 2024-02-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitTrack', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
