# Generated by Django 5.0.1 on 2024-02-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitTrack', '0013_bmrmeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basetable',
            fields=[
                ('basetable_id', models.AutoField(primary_key=True, serialize=False)),
                ('sodium_mg', models.IntegerField()),
                ('cholesterol_mg', models.CharField(max_length=100)),
                ('fiber_g', models.CharField(max_length=100)),
                ('calories', models.CharField(max_length=100)),
                ('fat_saturated_g', models.CharField(max_length=100)),
                ('sugar_g', models.CharField(max_length=100)),
                ('fat_total_g', models.CharField(max_length=100)),
                ('protein_g', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('serving_size_g', models.CharField(max_length=100)),
                ('carbohydrates_total_g', models.CharField(max_length=100)),
                ('potassium_mg', models.CharField(max_length=100)),
            ],
        ),
    ]
