# Generated by Django 5.0.1 on 2024-02-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitTrack', '0014_basetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basetable',
        ),
    ]
